const test=require('node:test'),assert=require('node:assert/strict'),E=require('../game/engine');
function g(){const s=E.createGame(['i','d1','d2'],'i');E.startAt(s,'vpn');return s}
test('movement validates adjacency and isolated nodes',()=>{let s=g();assert.throws(()=>E.intruderAction(s,{type:'stealth',node:'vault'}));s.isolated.push('ws1');assert.throws(()=>E.intruderAction(s,{type:'stealth',node:'ws1'}));E.intruderAction(s,{type:'stealth',node:'ws2'},()=>0);assert.equal(s.intruder.position,'ws2')});
test('isolation captures current intruder',()=>{let s=g();E.intruderAction(s,{type:'lieLow'},()=>0);E.socAction(s,'d1',{type:'isolate',node:'vpn'});assert.equal(s.winner,'soc')});
test('honeypot triggers critical exact-location alert',()=>{let s=g();E.intruderAction(s,{type:'lieLow'},()=>0);E.socAction(s,'d1',{type:'honeypot',node:'ws2'});E.socAction(s,'d2',{type:'skip',node:'vpn'});E.intruderAction(s,{type:'stealth',node:'ws2'},()=>0);assert.ok(s.alerts.some(a=>a.severity==='CRITICAL'&&a.message.includes('WS-02')))});
test('vault exfiltration wins after SOC phase',()=>{let s=g();s.intruder.position='dc';s.intruder.history.push({round:1,node:'dc'});E.intruderAction(s,{type:'stealth',node:'vault'},()=>0);E.socAction(s,'d1',{type:'investigate',node:'dc'});E.socAction(s,'d2',{type:'investigate',node:'db'});assert.equal(s.winner,'intruder')});
test('trapped intruder loses',()=>{let s=g();E.intruderAction(s,{type:'lieLow'},()=>0);s.isolated.push('ws1','ws2');E.socAction(s,'d1',{type:'investigate',node:'web'});E.socAction(s,'d2',{type:'investigate',node:'email'});assert.equal(s.winner,'soc');assert.match(s.reason,/trapped/)});
test('12-round timeout gives SOC win',()=>{let s=g();s.round=12;E.intruderAction(s,{type:'lieLow'},()=>0);E.socAction(s,'d1',{type:'investigate',node:'web'});E.socAction(s,'d2',{type:'investigate',node:'email'});assert.equal(s.winner,'soc');assert.match(s.reason,/12/)});
test('SOC public state contains no hidden position/path/alert truth',()=>{let s=g();E.intruderAction(s,{type:'stealth',node:'ws2'},()=>0);const p=E.publicState(s,'d1'),raw=JSON.stringify(p);assert.equal(p.position,undefined);assert.equal(p.history,undefined);assert.ok(!raw.includes('"kind"'));assert.ok(!raw.includes('ws2')||p.alerts.some(a=>a.message.includes('WS-02'))===false)});
