const express=require('express'),http=require('http'),{Server}=require('socket.io'),crypto=require('crypto'),path=require('path'),engine=require('./game/engine');const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,'public')));const rooms=new Map(),loops=new Map();const clean=s=>String(s||'').replace(/[<>"'&]/g,'').trim().slice(0,24);const makeCode=()=>{let c;do{c=Array.from({length:4},()=>String.fromCharCode(65+Math.floor(Math.random()*26))).join('')}while(rooms.has(c));return c};
function view(r){return{code:r.code,hostId:r.hostId,players:[...r.players.values()].map(p=>({id:p.id,nick:p.nick,connected:!!p.socketId})),game:r.game?engine.publicState(r.game):null}}
function emit(r){const v=view(r);for(const p of r.players.values())if(p.socketId)io.to(p.socketId).emit('state',v)}
function startLoop(r){clearInterval(loops.get(r.code));loops.set(r.code,setInterval(()=>{if(!r.game)return;engine.tick(r.game);emit(r);if(r.game.winner){clearInterval(loops.get(r.code));loops.delete(r.code)}},250))}
io.on('connection',socket=>{socket.on('createRoom',({playerId,nick},cb)=>{playerId=clean(playerId)||crypto.randomUUID();const c=makeCode(),r={code:c,hostId:playerId,players:new Map(),game:null};r.players.set(playerId,{id:playerId,nick:clean(nick)||'Commander',socketId:socket.id});rooms.set(c,r);socket.join(c);cb?.({ok:true,playerId,code:c});emit(r)});
socket.on('joinRoom',({code,playerId,nick},cb)=>{const r=rooms.get(String(code||'').toUpperCase());if(!r)return cb?.({ok:false,error:'Room not found'});playerId=clean(playerId)||crypto.randomUUID();let p=r.players.get(playerId);if(!p){if(r.game)return cb?.({ok:false,error:'Battle already started'});if(r.players.size>=2)return cb?.({ok:false,error:'Battle is full'});p={id:playerId,nick:clean(nick)||'Commander'};r.players.set(playerId,p)}p.socketId=socket.id;p.nick=clean(nick)||p.nick;socket.join(r.code);cb?.({ok:true,playerId,code:r.code});emit(r)});
socket.on('startGame',({code,playerId},cb)=>{const r=rooms.get(code);if(!r||r.hostId!==playerId)return cb?.({ok:false,error:'Host only'});if(r.players.size!==2)return cb?.({ok:false,error:'Need exactly 2 players'});const ids=[...r.players.keys()],names=Object.fromEntries([...r.players].map(([id,p])=>[id,p.nick]));r.game=engine.createGame(ids,names);cb?.({ok:true});emit(r);startLoop(r)});
socket.on('deploy',({code,playerId,card,lane},cb)=>{const r=rooms.get(code);if(!r?.game)return cb?.({ok:false,error:'No active battle'});try{engine.tick(r.game);engine.deploy(r.game,playerId,card,lane);cb?.({ok:true});emit(r)}catch(e){cb?.({ok:false,error:e.message})}});
socket.on('playAgain',({code,playerId},cb)=>{const r=rooms.get(code);if(!r||r.hostId!==playerId||!r.game?.winner)return cb?.({ok:false,error:'Host only'});const ids=[...r.players.keys()],names=Object.fromEntries([...r.players].map(([id,p])=>[id,p.nick]));r.game=engine.createGame(ids,names);cb?.({ok:true});emit(r);startLoop(r)});
socket.on('disconnect',()=>{for(const [code,r] of rooms){const p=[...r.players.values()].find(x=>x.socketId===socket.id);if(!p)continue;p.socketId=null;if(!r.game)r.players.delete(p.id);if(r.hostId===p.id&&r.players.size)r.hostId=[...r.players.keys()][0];if(!r.players.size){clearInterval(loops.get(code));loops.delete(code);rooms.delete(code)}else emit(r)}})});
const PORT=process.env.PORT||3000;if(require.main===module)server.listen(PORT,()=>console.log('CROWN//CLASH listening on '+PORT));module.exports={server,rooms,shutdown:()=>{for(const t of loops.values())clearInterval(t);loops.clear();rooms.clear();return new Promise(resolve=>io.close(()=>server.listening?server.close(()=>resolve()):resolve()))}};