const express=require('express');const http=require('http');const {Server}=require('socket.io');const crypto=require('crypto');const path=require('path');
const engine=require('./game/engine');const map=require('./game/map');
const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname,'public')));app.get('/api/map',(req,res)=>res.json({nodes:map.nodes,edges:map.edges}));
const rooms=new Map();const timers=new Map();const deadlines=new Map();
const clean=s=>String(s||'').replace(/[<>"'&]/g,'').trim().slice(0,24);const code=()=>{let c;do{c=Array.from({length:4},()=>String.fromCharCode(65+Math.floor(Math.random()*26))).join('')}while(rooms.has(c));return c};
function roomView(r,pid){const deadline=deadlines.get(r.code)||null;return {code:r.code,hostId:r.hostId,players:[...r.players.values()].map(p=>({id:p.id,nick:p.nick,connected:!!p.socketId,role:r.game?.phase==='gameover'||p.id===pid?p.role:undefined})),game:r.game?{...engine.publicState(r.game,pid),deadline}:null,chat:r.chat};}
function emitRoom(r){for(const p of r.players.values())if(p.socketId)io.to(p.socketId).emit('state',roomView(r,p.id));}
function arm(r){clearTimeout(timers.get(r.code));deadlines.delete(r.code);if(!r.game||r.game.winner)return;const ms=r.game.phase==='intruder'?45000:r.game.phase==='soc'?60000:0;if(!ms)return;deadlines.set(r.code,Date.now()+ms);timers.set(r.code,setTimeout(()=>timeout(r),ms));}
function timeout(r){if(!r.game||r.game.winner)return;if(r.game.phase==='intruder'){let a={type:'lieLow'};if(r.game.intruder.lastLieLow){const n=engine.legalNeighbors(r.game)[0];if(!n){engine.finishSocPhase(r.game);}else a={type:'stealth',node:n};}if(!r.game.winner)engine.intruderAction(r.game,a);}else{const soc=r.game.players.filter(p=>p.role==='soc');while(!r.game.winner&&r.game.phase==='soc'&&r.game.socActionsTaken<r.game.socActionsNeeded){const p=soc.find(x=>(x.actionsThisRound||0)<(soc.length===1?2:1));if(!p)break;engine.socAction(r.game,p.id,{type:'skip',node:'vpn'});}}emitRoom(r);arm(r);}
io.on('connection',socket=>{
 socket.on('createRoom',({playerId,nick},cb)=>{playerId=clean(playerId)||crypto.randomUUID();nick=clean(nick)||'Analyst';const c=code(),r={code:c,hostId:playerId,players:new Map(),chat:[],game:null};r.players.set(playerId,{id:playerId,nick,socketId:socket.id,role:null});rooms.set(c,r);socket.join(c);cb?.({ok:true,playerId,code:c});emitRoom(r)});
 socket.on('joinRoom',({code:cc,playerId,nick},cb)=>{const r=rooms.get(String(cc||'').toUpperCase());if(!r)return cb?.({ok:false,error:'Room not found'});playerId=clean(playerId)||crypto.randomUUID();let p=r.players.get(playerId);if(!p){if(r.game)return cb?.({ok:false,error:'Game already started'});if(r.players.size>=5)return cb?.({ok:false,error:'Room full'});p={id:playerId,nick:clean(nick)||'Analyst',role:null};r.players.set(playerId,p)}p.socketId=socket.id;p.nick=clean(nick)||p.nick;socket.join(r.code);cb?.({ok:true,playerId,code:r.code});emitRoom(r)});
 socket.on('startGame',({code:cc,playerId,intruderId,entry},cb)=>{const r=rooms.get(cc);if(!r||r.hostId!==playerId)return cb?.({ok:false,error:'Host only'});if(r.players.size<2)return cb?.({ok:false,error:'Need 2 players'});const ids=[...r.players.keys()];const iid=ids.includes(intruderId)?intruderId:ids[Math.floor(Math.random()*ids.length)];for(const p of r.players.values())p.role=p.id===iid?'intruder':'soc';r.game=engine.createGame(ids,iid);if(entry&&playerId===iid)engine.startAt(r.game,entry);cb?.({ok:true});emitRoom(r);if(r.game.phase!=='setup')arm(r)});
 socket.on('chooseEntry',({code:cc,playerId,node},cb)=>{const r=rooms.get(cc);if(!r||r.game?.intruderId!==playerId)return cb?.({ok:false,error:'Intruder only'});try{engine.startAt(r.game,node);cb?.({ok:true});arm(r);emitRoom(r)}catch(e){cb?.({ok:false,error:e.message})}});
 socket.on('action',({code:cc,playerId,action},cb)=>{const r=rooms.get(cc);if(!r?.game)return cb?.({ok:false,error:'No game'});try{const role=r.players.get(playerId)?.role;if(role==='intruder')engine.intruderAction(r.game,action);else engine.socAction(r.game,playerId,action);cb?.({ok:true});arm(r);emitRoom(r)}catch(e){cb?.({ok:false,error:e.message})}});
 socket.on('chat',({code:cc,playerId,text},cb)=>{const r=rooms.get(cc),p=r?.players.get(playerId);if(!r||!p||p.role!=='soc')return cb?.({ok:false,error:'SOC only'});const msg=clean(text).slice(0,160);if(msg){r.chat.push({nick:p.nick,text:msg,ts:Date.now()});r.chat=r.chat.slice(-50);emitRoom(r)}cb?.({ok:true})});
 socket.on('playAgain',({code:cc,playerId},cb)=>{const r=rooms.get(cc);if(!r||r.hostId!==playerId||!r.game?.winner)return cb?.({ok:false});const ids=[...r.players.keys()],old=r.game.intruderId,idx=ids.indexOf(old),iid=ids[(idx+1)%ids.length];for(const p of r.players.values())p.role=p.id===iid?'intruder':'soc';r.game=engine.createGame(ids,iid);deadlines.delete(r.code);cb?.({ok:true});emitRoom(r)});
 socket.on('disconnect',()=>{for(const [c,r] of rooms){const p=[...r.players.values()].find(x=>x.socketId===socket.id);if(!p)continue;p.socketId=null;if(!r.game)r.players.delete(p.id);if(r.hostId===p.id&&r.players.size)r.hostId=[...r.players.keys()][0];if(!r.players.size){clearTimeout(timers.get(c));timers.delete(c);deadlines.delete(c);rooms.delete(c)}else emitRoom(r)}});
});
const PORT=process.env.PORT||3000;if(require.main===module)server.listen(PORT,()=>console.log(`BREACH listening on ${PORT}`));module.exports={server,rooms,shutdown:()=>{for(const t of timers.values())clearTimeout(t);timers.clear();deadlines.clear();rooms.clear();return new Promise(resolve=>io.close(()=>server.listening?server.close(()=>resolve()):resolve()))}};